### ISSUE TITLE
Simplify the $('body').keyup()'s

### ISSUE THREAD

**Issue by Ryan104** [miketheo423/rock-paper-scissors#6]
I think separate `$('body').keyup(function(e) { ... }` are not necessary. You should be able to put all of your `if` statements checking the key inside one jQuery event to clean things up.

Also, you could group all the `if` statements inside one `if (sec > 0)` instead of checking that in every conditional with `&&`.

**Comment by miketheo423** [comment]
Put all if statements inside of one function and only used the if (sec > 0) once.
